name: KylaChristmasTree
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: any

dev_dependencies:
  pedantic: any
